apiVersion: 0.1
kind: Deployment
name: WSO2 Identity Server Pattern 1
codeName: wso2is-pattern-1
version: 5.4.0
components:
-
  name: MySQL
  codeName: mysql
  version: 5.7.19
  cpu: 2
  memory: 2G
  disk: 20G
  image: mysql:5.7.19
  environment:
  - MYSQL_ROOT_PASSWORD=wso2carbon
  replicas: 1
  scalable: false
  clustering: false
  ports:
  -
    name: jdbc
    protocol: TCP
    port: 3306
    external: false
  volumes:
    - ./mysql/scripts:/docker-entrypoint-initdb.d
  healthcheck:
    command:
      assertion: ["CMD", "mysqladmin" ,"ping", "-uroot", "-pwso2carbon"]
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 60
-
  name: WSO2 Identity Server 1
  codeName: identity-server-1
  version: 5.4.0
  cpu: 4
  memory: 4G
  disk: 10G
  distribution: wso2is-2.1.0.zip
  entrypoint: bin/wso2server.sh
  image: wso2is:5.4.0
  environment:
    - EXCLUDE_PORTS=4000,9763
    - VIRTUAL_HOST=https://wso2is
    - EXTRA_ROUTE_SETTINGS=ssl check verify none
    - BALANCE=source
  replicas: 1
  scalable: false
  clustering: false
  ports:
  -
    name: servlet-http
    protocol: HTTP
    port: 9763
    external: true
    sessionAffinity: true
  -
    name: servlet-https
    protocol: HTTPS
    port: 9443
    external: true
    sessionAffinity: true
  -
    name: hazelcast
    protocol: TCP
    port: 4000
    external: false
    sessionAffinity: false
  databases:
  -
    name: WSO2IS-DB
    type: MySQL
    version: 5.7.19
    createScript: database-scripts/apim-db.sql
  volumes:
    - ./identity-server/repository/components/lib/mysql-connector-java-5.1.34-bin.jar:/home/wso2carbon/wso2is-5.3.0/repository/components/lib/mysql-connector-java-5.1.34-bin.jar
    - ./identity-server/repository/conf/carbon.xml:/home/wso2carbon/wso2is-5.3.0/repository/conf/carbon.xml
    - ./identity-server/repository/conf/axis2/axis2-1.xml:/home/wso2carbon/wso2is-5.3.0/repository/conf/axis2/axis2.xml
    - ./identity-server/repository/conf/datasources/master-datasources.xml:/home/wso2carbon/wso2is-5.3.0/repository/conf/datasources/master-datasources.xml
    - ./identity-server/repository/conf/tomcat/catalina-server.xml:/home/wso2carbon/wso2is-5.3.0/repository/conf/tomcat/catalina-server.xml
  dependencies:
  -
    component: mysql
    ports:
    - jdbc
  healthcheck:
    httpGet:
      path: /carbon/admin/login.jsp
      port: 9443
    initialDelaySeconds: 120
    periodSeconds: 5
    timeoutSeconds: 120
-
  name: WSO2 Identity Server 2
  codeName: identity-server-2
  version: 5.4.0
  cpu: 4
  memory: 4G
  disk: 10G
  distribution: wso2is-2.1.0.zip
  entrypoint: bin/wso2server.sh
  image: wso2is:5.4.0
  environment:
    - EXCLUDE_PORTS=4000,9763
    - VIRTUAL_HOST=https://wso2is
    - EXTRA_ROUTE_SETTINGS=ssl check verify none
    - BALANCE=source
  replicas: 1
  scalable: false
  clustering: false
  ports:
  -
    name: servlet-http
    protocol: HTTP
    port: 9763
    external: true
    sessionAffinity: true
  -
    name: servlet-https
    protocol: HTTPS
    port: 9443
    external: true
    sessionAffinity: true
  -
    name: hazelcast
    protocol: TCP
    port: 4000
    external: false
    sessionAffinity: false
  databases:
  -
    name: WSO2IS-DB
    type: MySQL
    version: 5.7.19
    createScript: database-scripts/apim-db.sql
  volumes:
    - ./identity-server/repository/components/lib/mysql-connector-java-5.1.34-bin.jar:/home/wso2carbon/wso2is-5.3.0/repository/components/lib/mysql-connector-java-5.1.34-bin.jar
    - ./identity-server/repository/conf/carbon.xml:/home/wso2carbon/wso2is-5.3.0/repository/conf/carbon.xml
    - ./identity-server/repository/conf/axis2/axis2-2.xml:/home/wso2carbon/wso2is-5.3.0/repository/conf/axis2/axis2.xml
    - ./identity-server/repository/conf/datasources/master-datasources.xml:/home/wso2carbon/wso2is-5.3.0/repository/conf/datasources/master-datasources.xml
    - ./identity-server/repository/conf/tomcat/catalina-server.xml:/home/wso2carbon/wso2is-5.3.0/repository/conf/tomcat/catalina-server.xml
  dependencies:
  -
    component: mysql
    ports:
    - jdbc
  -
    component: identity-server-1
    ports:
    - hazelcast
  healthcheck:
    httpGet:
      path: /carbon/admin/login.jsp
      port: 9443
    initialDelaySeconds: 120
    periodSeconds: 5
    timeoutSeconds: 120
-
  name: Load Balancer
  codeName: lb
  image: dockercloud/haproxy:1.6.3
  ports:
    -
      name: https
      protocol: HTTPS
      port: 443
  environment:
    - TIMEOUT=connect 50000, client 50000, server 50000
    - STATS_AUTH=stats:stats
    - |
      DEFAULT_SSL_CERT=-----BEGIN PRIVATE KEY-----
      MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC7wjNL42p/GkYM
      CBodUEp2posvmY0zZZefQepcGo6Gy2/5CdJup2oPyk9j3Xlzhf3YgBdRxeez+319
      +BRTAzlNV1ZSWXJi+ixQ46rp8v8SmUjNk+os9f7LJAjt8/DuEqNQOSw7jDQ/E4Bi
      t4mFsdttV8c5eetcUH6NPMoj2RsEEutlzSRubDDYoDb4naSx0kGm6R8r3pVuRE/s
      kt44j7VNjls07QCjoNwSZtIa6YbkTspbS1OHPBuoMM7PnXMQCpojbHl01LdZyn8b
      6LWKIZPYuEtm2Nt4ARi3+Q+RPyc7BgFnUJY7IL7ZI4alRJj43qWX9jEmZi2HuPqs
      tVeCtKbpAgMBAAECggEBAJyEPw67/UMHO+07s8lL7UcLfmunrTVzMvnnkN5GpRlo
      7WbE8U6c8KVJGPU+4seSoxGfddENESHQO8SO0SKCRXpbm/H57ojj0516rDdqAYgX
      j8EP1N62Ejh1SZxTBjzv/IQbpOve7I7ISvX/2fxBT5HO4pzfLXw+/b/vNPK9QPAb
      B7jFqrjfmJps4DPRZ6oJHuQ7SuzK9SCA3RxnTQtZggfnFYLOYVmFR8mz0e+Ysvl9
      dI9QO31D8YLvy8NcBdLqAkYuO/KMPIIBnvY29Bvag/FV+6LctTESn1UZCJrCaUIO
      GI3SmSkq/BoqklKX7kLOxhnfDiQQin4GnuVmCwurcIECgYEA4nX+/hy0BrNv+rnO
      NyRFjYqIrNCozV+qH1loBXN0CrxZrHmAvQ/65HQcL3iarfJ6G5z7DDH09TAhkdFr
      Gr5T9BYr3A3YQc1TqlzTfuTzOuvcr+D0RpcrGONTwHA/BA00YYKR+uHThX/jTUdy
      SngOVyu+LZYqlISvcJ6ox7IwDSUCgYEA1D/aR3b4hfEhamOKSQY3mnHMwEqwKwtj
      SD35zoYGH5h5G9k0/Qa9imKrhcpU+7j18V+Pnm11tw/zlCxhwsATl7F7PB6PYDoJ
      44RjQDqS7StD1glb3ZOJyTaPgJge5URG1bTvAe8BjNiQRpNEhq8DBbHO7/Fn4Hga
      wqRGSjrzgXUCgYBcF3XxqoR/MRs5j7PPcr2iGJMKC/SJR/zrsLT/enrXHs8st2Bm
      AgiaPKl1mIr2b+O+NPFWfT5LMx6DqPDwODP1z8pYO30VDUWXwxXyxXIwJNhi4Y0U
      48aP4WoemMbXg/MoMCvjJVCaOm6Z75MHu5jBVDWLXkTEjsy1dJ/YTZsCzQJ/FLon
      ltMHcg0aNkmCN59jzrFOTXj9uzZhe6yRuJld/7fkG9QaWJtP5zO7jFU1918YpXmv
      jMkjtbzZDJ9I7LvVLfsnDbfuSHdif9Vt29fcgUy4Uy6WygyeaAfr+6LfYYRJZpVE
      weuVOyvq6vl2t7Bfmy7CBqyMeF9CPb/NHXKkVQKBgQC6L1oEyyEyrB5LkO0Zm3wU
      Sy9c+uMxaWmAtCW096y/PLp0iDgpE/w9PQcMZc5OTjAAZqltX/9f5AQMENv6kxEL
      1f/3zMbxBpdM6RqxDO9Kl3YeMZv824BOIOR1VWXDqYCOKP0YtLbMYSbBWVzrl9qe
      R/PoA21O82EAvD5Z3MEjjw==
      -----END PRIVATE KEY-----
      -----BEGIN CERTIFICATE-----
      MIIC1jCCAb4CCQCiPjYDnGowjTANBgkqhkiG9w0BAQsFADAtMQowCAYDVQQDDAEq
      MRIwEAYDVQQKDAlXU08yIEluYy4xCzAJBgNVBAYTAlVTMB4XDTE3MTIwNjE1NDEy
      M1oXDTIwMTEyMDE1NDEyM1owLTEKMAgGA1UEAwwBKjESMBAGA1UECgwJV1NPMiBJ
      bmMuMQswCQYDVQQGEwJVUzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
      ALvCM0vjan8aRgwIGh1QSnamiy+ZjTNll59B6lwajobLb/kJ0m6nag/KT2PdeXOF
      /diAF1HF57P7fX34FFMDOU1XVlJZcmL6LFDjquny/xKZSM2T6iz1/sskCO3z8O4S
      o1A5LDuMND8TgGK3iYWx221Xxzl561xQfo08yiPZGwQS62XNJG5sMNigNvidpLHS
      QabpHyvelW5ET+yS3jiPtU2OWzTtAKOg3BJm0hrphuROyltLU4c8G6gwzs+dcxAK
      miNseXTUt1nKfxvotYohk9i4S2bY23gBGLf5D5E/JzsGAWdQljsgvtkjhqVEmPje
      pZf2MSZmLYe4+qy1V4K0pukCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAAP9yG3rG
      6/dVei8EbBapfJKsaWmw+dQ1GACyf0954JvYvSByCZnOsIhAYBYJDg6Cu++aINoj
      ufYoP0aEhMnh+XxmLxKeiIMhKJuOdRabh8JFNoigfYBVp8O54d84/C0yTEMovzr6
      jgrYWU7NCgomV9lQt4SYK3M4iUOltPkswNAgC53jUMriXkj+rS3xE/6LD+t2nSmQ
      tFA9j5VTLNVYo3pwRf9nAAaFNNBU05cNUsmml82JnaAnD+mPAkUqI57KSQhhZNUF
      X1f1eTCNZfOvmIV5/enIkXpwXLj+TRiOs1/kwcUfIA+jV6g5WRCJHaIi514weKLI
      DNanJQQSvc34ow==
      -----END CERTIFICATE-----
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  dependencies:
    -
      component: identity-server-2
      ports:
      - https-servlet

